browser = chrome

urlOrangehr = https://opensource-demo.orangehrmlive.com/web/index.php/auth/login
urlUserinyerface = https://userinyerface.com

userNameAdmin = Admin
passwordAdmin = admin123

imgToUploadPath = \\src\\main\\resources\\images\\ImgToUpload.png