package com.qa.orangehr.tests;

import com.microsoft.playwright.*;
import com.microsoft.playwright.junit.UsePlaywright;
import com.microsoft.playwright.options.AriaRole;
import org.junit.jupiter.api.*;
import java.nio.file.Paths;
import static com.microsoft.playwright.assertions.PlaywrightAssertions.assertThat;
import static org.junit.jupiter.api.Assertions.assertEquals;


@UsePlaywright
class FirstTests11 {
    @Test
    void differentControlsExerciseNonPom() {
        try (Playwright playwright = Playwright.create()) {
            Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions()
                    .setHeadless(false)
                    .setSlowMo(150)
            );
            Page page = browser.newPage();
            page.navigate("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
            page.waitForSelector("h5[class=\"oxd-text oxd-text--h5 orangehrm-login-title\"]");
            page.getByText("Login");
            page.fill("input[name = 'username']", "Admin");
            page.fill("input[name = 'password']", "admin123");
            page.click("button[type='submit']");
            page.waitForURL("https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index");

            assertThat(page).hasTitle("OrangeHRM");
        }
    }

    @Test
    void checkSearch() {
        try (Playwright playwright = Playwright.create()) {
            Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions()
                    .setHeadless(false)
                    .setSlowMo(150)
            );
            Page page = browser.newPage();
            page.navigate("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
            page.waitForSelector("h5[class=\"oxd-text oxd-text--h5 orangehrm-login-title\"]");
            page.fill("input[name = 'username']", "Admin");
            page.fill("input[name = 'password']", "admin123");
            page.click("button[type='submit']");
            page.waitForURL("https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index");
            page.getByPlaceholder("Search").fill("Ad");
            int ulCount = page.locator("div[class= 'oxd-sidepanel-body']").locator("ul").count();

            assertEquals(1, ulCount);
        }
    }


    @Test
    void autoGeneratedTestWithTracing(){
        //exec in cmd from folder with maven (in args paste url of the site): >mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="codegen https://opensource-demo.orangehrmlive.com/web/index.php/auth/login"
        try (Playwright playwright = Playwright.create()) {
            Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions()
                    .setHeadless(false));
            BrowserContext context = browser.newContext();

            //Tracing code
            context.tracing().start(new Tracing.StartOptions()
                    .setScreenshots(true)
                    .setSnapshots(true)
                    .setSources(true));

            Page page = context.newPage();
            page.navigate("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
            page.getByPlaceholder("Username").click();
            page.getByPlaceholder("Username").fill("Admin");
            page.getByPlaceholder("Password").click();
            page.getByPlaceholder("Password").fill("admin123");
            page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Login")).click();
            page.getByPlaceholder("Search").click();
            page.getByPlaceholder("Search").fill("Di");
            page.getByRole(AriaRole.LINK, new Page.GetByRoleOptions().setName("Directory")).click();
            page.getByText("-- Select --").first().click();
            page.getByText("Account Assistant").click();
            page.locator(".oxd-sheet").first().click();

            //assertThat(page.getByText("yedghjb1 ru84 90jsnd").first()).isVisible();

            // Stop tracing and export it into a zip archive.
            context.tracing().stop(new Tracing.StopOptions()
                    .setPath(Paths.get("trace.zip")));
        }
    }
}
